# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    memcached:
        class: Memcached
        calls:
            - [addServers, [%memcached_servers%]]
    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [setMemcached, [@memcached]]
    json_exception_listener:
        class: AppBundle\Kernel\JsonExceptionListener
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200}
    service:
        class: AppBundle\Common\Service
        abstract: true
        calls:
          - [setContainer, [@service_container]]
    registryapi.user:
        class: AppBundle\Service\UserService
        parent: service
    registryapi.registry:
        class: AppBundle\Service\RegistryService
        parent: service
    registryapi.status:
        class: AppBundle\Service\StatusService
        parent: service
    registryapi.type:
        class: AppBundle\Service\TypeService
        parent: service
    registryapi.entry:
        class: AppBundle\Service\EntryService
        parent: service
    registryapi.category:
        class: AppBundle\Service\CategoryService
        parent: service
    registryapi.association:
        class: AppBundle\Service\AssociationService
        parent: service
    registryapi.address:
        class: AppBundle\Service\AddressService
        parent: service
