# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #memcached:
        #class: Memcached
        #calls:
            #- [addServers, [%memcached_servers%]]
    #doctrine.cache.memcached:
        #class: Doctrine\Common\Cache\MemcachedCache
        #calls:
            #- [setMemcached, [@memcached]]
    json_exception_listener:
        class: AppBundle\Kernel\JsonExceptionListener
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200}
    service:
        class: AppBundle\Common\Service
        abstract: true
        calls:
          - [setContainer, [@service_container]]
    registryapi.user:
        class: AppBundle\Service\UserService
        parent: service
    registryapi.registry:
        class: AppBundle\Service\RegistryService
        parent: service
    registryapi.entry:
        class: AppBundle\Service\EntryService
        arguments: ['AppBundle\Entity\Entry']
        parent: service
    registryapi.connectionType:
        class: AppBundle\Service\ConnectionTypeService
        parent: service
    registryapi.connection:
        class: AppBundle\Service\ConnectionService
        arguments: ['AppBundle\Entity\Connection']
        parent: service
    registryapi.address:
        class: AppBundle\Service\AddressService
        parent: service
    registryapi.directory:
        class: AppBundle\Service\DirectoryService
        parent: service
    registryapi.property:
        class: AppBundle\Service\PropertyService
        parent: service
    registryapi.propertyGroup:
        class: AppBundle\Service\PropertyGroupService
        parent: service
