# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #memcached:
        #class: Memcached
        #calls:
            #- [addServers, [%memcached_servers%]]
    #doctrine.cache.memcached:
        #class: Doctrine\Common\Cache\MemcachedCache
        #calls:
            #- [setMemcached, ['@memcached']]
    json_exception_listener:
        class: AppBundle\Kernel\JsonExceptionListener
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200}
    user_provider:
        class: AppBundle\Security\User\UserProvider
        arguments:
            - '@doctrine'
            - 'AppBundle:User'
            - 'username'
    registryapi.service:
        class: AppBundle\Common\Service
        abstract: true
        calls:
            - [setContainer, ['@service_container']]
    registryapi.user:
        class: AppBundle\Service\UserService
        arguments: ['AppBundle\Entity\User']
        parent: registryapi.service
    registryapi.registry:
        class: AppBundle\Service\Common\JSendService
        arguments: ['AppBundle\Entity\Registry']
        parent: registryapi.service
    registryapi.entry:
        class: AppBundle\Service\EntryService
        arguments: ['AppBundle\Entity\Entry']
        parent: registryapi.service
    registryapi.connectionType:
        class: AppBundle\Service\Common\JSendService
        arguments: ['AppBundle\Entity\ConnectionType']
        parent: registryapi.service
    registryapi.connection:
        class: AppBundle\Service\Common\JSendService
        arguments: ['AppBundle\Entity\Connection']
        parent: registryapi.service
    registryapi.address:
        class: AppBundle\Service\Common\JSendService
        arguments: ['AppBundle\Entity\Address']
        parent: registryapi.service
    registryapi.property:
        class: AppBundle\Service\Common\JSendService
        arguments: ['AppBundle\Entity\Property']
        parent: registryapi.service
    registryapi.propertyGroup:
        class: AppBundle\Service\Common\JSendService
        arguments: ['AppBundle\Entity\PropertyGroup']
        parent: registryapi.service
    registryapi.invoice:
        class: AppBundle\Service\InvoiceService
        parent: registryapi.service
